default_platform(:ios)

platform :ios do
	before_all do
    		setup_ci
	end
	
	desc "Run all unit tests"

	lane :unit_tests do
	  scan(
	      project: "FastLaneBootcamp.xcodeproj",
	      scheme: "FastLaneBootcamp",
	      only_testing: [
			     "FastLaneBootcampTests"
			    ]
	     )
	end

	desc "Create an archive and export"
	lane :build do
	  gym(
	      project: "FastLaneBootcamp.xcodeproj",
	      scheme: "FastLaneBootcamp"
	      )
	end
 
   desc "Run tests and build the application"
   lane :ci do
        api_key = app_store_connect_api_key(
            key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
            issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
            key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
            is_key_content_base64: false
          )
        match(type: "appstore", readonly: true)
        unit_tests
        build
        pilot(
            api_key: api_key,
  	    distribute_external: false,
  	    submit_beta_review: false
            )
    end

end
