name: iOS CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0'
          bundler-cache: true

      - name: Run CI
        env:
            MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
            MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
            APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
            APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
            APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}

        run: bundle exec fastlane ci
    
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: FastLaneBootcamp-IPA
          path: FastLaneBootcamp.ipa

      - name: Upload dSYM
        uses: actions/upload-artifact@v4
        with:
          name: FastLaneBootcamp-dSYM
          path: FastLaneBootcamp.app.dSYM.zip
